apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: python
  name: python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-helloworld
  namespace: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-helloworld
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - name: python-helloworld
        image: srashidmrgacr.azurecr.io/python-container-starter-env:v1.01
        ports:
        - containerPort: 5858
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
          - name: SECRET_MESSAGE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: message
---
apiVersion: v1
kind: Service
metadata:
  name: python-helloworld
  namespace: python
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5858
  selector:
    app: python-helloworld
